name: run-tests
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests for contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests for std-2
        uses: EthereumRemix/sol-test@v1
        with:
            test-path: 'std-2/tests'
            compiler-version: '0.8.17'